version: '3.7'

services:

  php-blog:
    container_name: php-blog
    build:
      context: ./php
    ports:
      - '9001:9000'
    volumes:
      - ./app:/var/www/project
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - app-network

  nginx-blog:
    container_name: nginx-blog
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-blog
    networks:
      - app-network

networks:
  app-network:
    driver: bridge