parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\ExceptionListener:
        arguments:
            $twig: '@twig'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }
