services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\ExceptionListener:
        arguments:
            $twig: '@twig'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }

    App\EventListener\RateLimiterListener:
        arguments:
            $rateLimiter: '@limiter.default'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }

    App\Service\BlogService:
        arguments:
            $projectDir: '%kernel.project_dir%'