parameters:
    domain_name: '%env(DOMAIN_NAME)%'
    domain_url: '%env(DOMAIN_URL)%'
    blog_email: '%env(BLOG_EMAIL)%'
    work_email: '%env(WORK_EMAIL)%'
    linkedin_url: '%env(LINKEDIN_URL)%'
    github_url: '%env(GITHUB_URL)%'
    instagram_url: '%env(INSTAGRAM_URL)%'
    messenger_url: '%env(MESSENGER_URL)%'

    music_url: '%env(MUSIC_URL)%'
    book_url: '%env(BOOK_URL)%'
    game_url: '%env(GAME_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\ExceptionListener:
        arguments:
            $twig: '@twig'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }

    App\EventListener\RateLimiterListener:
        arguments:
            $rateLimiter: '@limiter.default'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }

    App\Service\BlogService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Twig\EnvTwigExtension:
        tags: [ 'twig.extension' ]