framework:
    cache:
        pools:
            default_cache_pool:
                default_lifetime: 180 # 3 minutes
                adapters:
                    - cache.adapter.apcu # persistent cache between requests