framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: strict

    php_errors:
        log: false

    router:
        utf8: true

    default_locale: en

    http_cache:
        enabled: true
        default_ttl: 3600

    profiler:
        only_exceptions: false

    disallow_search_engine_index: false